### PR TITLE
Make windows specific code for NoXS compile under strict

### LINKED ISSUE #365: t/lib/MakeMaker/Test/NoXS.pm does not compile on windows
As a result of the combination of 81d3c0c41d8005ee5ece0c01e0202c14f31c7605 and 67a6b5820e2f434db5ae52e3b06c0b522d454de3, this file no longer compiles on windows. I'll submit a PR with a fix in a few minutes.

```
C:\perl\cpan\ExtUtils-MakeMaker\t>perl -Ilib -MMakeMaker::Test::NoXS -e1
Can't use string ("Win32::GetCwd") as a symbol ref while "strict refs" in use at lib/MakeMaker/Test/NoXS.pm line 17.
Compilation failed in require.
BEGIN failed--compilation aborted.
```

### PR DESCRIPTION
**Pull request by toddr**
Fixes #365

### CODE REVIEW

**Comment by Grinnz** [comment]
Looks correct (and much cleaner) to me

File: t/lib/MakeMaker/Test/NoXS.pm [hunk 1]
```diff
@@ -13,12 +13,13 @@ require XSLoader;
...
 
 if ($^O eq 'MSWin32') {
+    # Load Win32. Backup GetCwd and SetChildShowWindow. Then clear the stash of all other entries.
     require Win32;
-    my $GetCwd = *{'Win32::GetCwd'}{CODE};
-    my $SetChildShowWindow = *{'Win32::SetChildShowWindow'}{CODE};
-    %{*main::Win32::{HASH}} = ();
-    *{'Win32::GetCwd'} = $GetCwd;
-    *{'Win32::SetChildShowWindow'} = $SetChildShowWindow;
+    my $GetCwd = Win32->can('GetCwd');
```
Comment (Leont) [inline t/lib/MakeMaker/Test/NoXS.pm:18]: How about `\&Win32::GetCwd`?

Comment (toddr) [reply t/lib/MakeMaker/Test/NoXS.pm:18]: Is this a stylistic comment or is there a difference?

Comment (Grinnz) [reply t/lib/MakeMaker/Test/NoXS.pm:18]: It's a direct reference to the function so closer to what the original code did; there's no reason to care about inheritance here and the function names are static so no need for `->can` really.

File: t/lib/MakeMaker/Test/NoXS.pm [hunk 2]
```diff
@@ -13,12 +13,13 @@ require XSLoader;
...
+    my $SetChildShowWindow = Win32->can('SetChildShowWindow');
+    %Win32:: = ();
+    *Win32::GetCwd = $GetCwd;
```
Comment (haarg) [inline t/lib/MakeMaker/Test/NoXS.pm:21]: This doesn't work. It binds early, so the glob it's assigning to gets erased by the stash being cleared.

**Comment by wolfsage** [comment]
Test

**Review by wchristian — CHANGES_REQUESTED** [review]

File: t/lib/MakeMaker/Test/NoXS.pm (hunk 2 above)
Comment (haarg) [reply t/lib/MakeMaker/Test/NoXS.pm:21]: `*Win32::GetCwd` binds to the glob at compile time. Clearing the stash removes that glob from the namespace, but because it's already bound, the assignment stores the sub in a glob that isn't in the namespace anymore.

**Comment by haarg** [comment]
```
delete @Win32::{ grep { $_ ne "GetCwd" && $_ ne "SetChildShowWindow" } keys %Win32:: };
```

File: t/lib/MakeMaker/Test/NoXS.pm (hunk 1 above)
Comment (toddr) [reply t/lib/MakeMaker/Test/NoXS.pm]: I have removed the use of can.

File: t/lib/MakeMaker/Test/NoXS.pm (hunk 2 above)
Comment (toddr) [reply t/lib/MakeMaker/Test/NoXS.pm]: Fair enough. Let's just not delete them to begin with as a solution?

**Comment by toddr** [comment]
> delete @Win32::{ grep { $_ ne "GetCwd" && $_ ne "SetChildShowWindow" } keys %Win32:: };

Yep. saw this late. I decided the for loop would be more clear to people?

**Review by wchristian — APPROVED** [review]

**Comment by wchristian** [comment]
Fwiw, i didn't mean to start a review. I am not sure how to use that interface. So i now clicked around on a few things and hope that made things better. :)

**Comment by haarg** [comment]
Technically this looks fine.  It might be worth explaining why the deletion is being done. Possibly something like:
```
# SetChildShowWindow and GetCwd are provided by perl core in modern perls, so we
# can use them in miniperl. on older perls, we can load them from Win32 so the
# test can proceed as normal.
```

**Comment by toddr** [comment]
> # SetChildShowWindow and GetCwd are provided by perl core in modern perls, so we
> # can use them in miniperl. on older perls, we can load them from Win32 so the
> # test can proceed as normal.

Part of my problem here was divining what @bulk88 's original intent was here. Is this for sure what's being done?

**Comment by haarg** [comment]
Yes.

The test is to verify that EUMM works properly in miniperl, which is before any XS modules are available. SetChildShowWindow and GetCwd are provided directly by perl on modern perls, not by the Win32 module. So they are allowed to be used by EUMM under miniperl. However, older perls don't provide them. Loading the Win32 module, then removing all of the other symbols simulates the situation on newer perls, which allows the miniperl test to continue normally. The miniperl behavior is only needed at perl build time, so simulating a modern perl is acceptable for testing. Current EUMM won't ever be used for building older perls.

**Comment by toddr** [comment]
comment updated.
